services:
  database:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 3s
      retries: 5
      
  backend:
    image: "ghcr.io/${OWNER}/sp16_backend:latest"
    restart: unless-stopped
    environment:
      PORT: ${BACKEND_INTERNAL_PORT}
      DEBUG: ${BACKEND_DEBUG}
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT_INTERNAL}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${BACKEND_PORT}:${BACKEND_INTERNAL_PORT}"
    volumes:
      - afisha_data:/app/public/content/afisha
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: "ghcr.io/${OWNER}/sp16_frontend:latest"
    restart: unless-stopped
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}
      VITE_API_URL: ${VITE_API_URL}
      VITE_CDN_URL: ${VITE_CDN_URL}
    volumes:
      - frontend_build:/var/www
    networks:
      - internal

  server:
    image: "ghcr.io/${OWNER}/sp16_server:latest"
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - frontend_build:/var/www:ro
      - afisha_data:/var/data/content/afisha:ro
    depends_on:
      - frontend
      - backend
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - internal

volumes:
  db_data:
  pgadmin-data:
  frontend_build:
  afisha_data:

networks:
  internal: